In [3]:
##
Employee1 = {'Employee_ID':1,'Emp_Name':"ABC",
             'Profession':"Developer"}
Employee2 = {'Employee_ID':2,'Emp_Name':"XYZ"
             ,'Profession':"Tester"}
str(Employee1)

"{'Employee_ID': 1, 'Emp_Name': 'ABC', 'Profession': 'Developer'}"

In [14]:
a=10
if a==10:
    print("inside if statment")
print("outside stat")

inside if statment
outside stat


In [17]:
if a==5:
    print("a is 5")
else:
    print("a is not 5")


a is 5


In [26]:
print("hi",end="@")
print("hello")

hi@hello


In [29]:
123456//10
10%2

0

In [25]:
n=5
for n in range(0,n):
    for j in range(0,i+1)
    



SyntaxError: invalid syntax (<ipython-input-25-e0e35e4ae499>, line 3)

In [ ]:
c=0
while(c<5):
    print(c)
    c += 1
else:
    print("C VALUE REACHED")

In [ ]:
for a range from (1,6):
    print(num)

In [1]:
import numpy as np
big_array=np.random.randint(1,100,size=100000)
%timeit(1.0/big_array)

156 µs ± 3.66 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
import numpy as np
x=np.arange(5)
print(x)
print(x*2)##multiplication
print(x**2)##power
print(x%2)##reminder

[0 1 2 3 4]
[0 2 4 6 8]
[ 0  1  4  9 16]
[0 1 0 1 0]
